### ISSUE TITLE
UnsatisfiedLinkError on mac

### ISSUE THREAD

**Issue by lulujiang** [opencv-java/getting-started#1]
I have done everything according to the doc.I can find a file named libopencv_java310.so in /path/to/opencv-3.1.0/build/lib.
Also ,I configured the Native library path to /path/to/opencv-3.1.0/build/lib in eclipse.

but after running he HelloCV project,an error below occured:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java310 in java.library.path.

**Comment by luigidr** [comment]
Hi, the `/path/to/opencv-3.1.0` is to be replaced with the _specific_ path on your computer. For example, if you installed opencv-3.1.0 in `/Applications/opencv` you have to insert `/Applications/opencv/build/lib`.
