### ISSUE TITLE
How to display IplImage in Imageview

### ISSUE THREAD

**Issue by mahajandhiraj** [opencv-java/getting-started#11]
I am trying to display IplImage on imageview in application. But Imageview_id.setImage() allows only Image obj as parameter. Is there is another method to display iplImage in imageview ? or How to convert IplImage to Image?

**Comment by luigidr** [comment]
Hi,

here you can find a method for converting an OpenCV `Mat` into a JavaFX `image`: https://github.com/opencv-java/getting-started/blob/master/FXHelloCV/src/it/polito/elite/teaching/cv/utils/Utils.java

You can try if this work with `IplImage`, as well. Please, notice that this project uses OpenCV 3.x (for Java) and JavaFX 8.

**Comment by mahajandhiraj** [comment]
channels = original.channels() 
and  
original.get(0, 0, sourcePixels); 
this two methods =>  channels() and get() are not predifined for IplImage

@luigidr 
Do you know any similar methods to replace this methods??

**Comment by luigidr** [comment]
No, unfortunately I don't know how to replace such methods.
`IplImage` existed for OpenCV 1.x and, perhaps, in some external OpenCV wrappers (in something like JavaCV?).
